export const PRODUCTS = [
  {
    categoryId: 3,
    description: "vin effervescent italien, idéal pour l'apéritif!",
    enabled: false,
    label: "Prosecco",
    order: 5,
    pictogramUrl:
      "https://storage.googleapis.com/selene-dev/product-pictograms/PRF/H38.png",
    price1: 5.5,
    price1Label: "coupe 12 cl",
    price2: 26,
    price2Label: "btlle 75 cl",
    price3: null,
    price3Label: null,
    price4: null,
    price4Label: null,
    price5: null,
    price5Label: null,
    productId: 84745,
  },
  {
    productId: 85700,
    categoryId: 3,
    label: "Stella Artois",
    description: null,
    order: 0,
    enabled: true,
    pictogramUrl: null,
    price1Label: "25cl",
    price1: 3.9,
    price2Label: "50cl",
    price2: 6.5,
    price3Label: "1l",
    price3: 10,
    price4Label: null,
    price4: null,
    price5Label: null,
    price5: null,
  },
];

export const CATEGORIES = [
  {
    categoryId: 1,
    parentId: null,
    description: "Les boissons",
    order: 1,
    enabled: true,
  },
  {
    categoryId: 2,
    parentId: 1,
    description: "Les bières",
    order: 1,
    enabled: false,
  },
  {
    categoryId: 3,
    parentId: 2,
    description: "Les bières blondes",
    order: 1,
    enabled: false,
  },
];
